development:
  database: acn_development
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  username: dev
  password: password

test: &test
  database: acn_test<%=ENV['TEST_ENV_NUMBER']%>
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  username: dev
  password: password

cucumber:
  <<: *test